os: windows
language: shell
before_install:
  - choco install python
  - python -m pip install --upgrade pip
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  script: pyinstaller "Number-Plate-Anonymiser/main.spec"
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: "dist/*.exe"
  skip_cleanup: true
  on:
    tags: true