os: windows
language: shell
before_install:
  - choco install python --version=3.7.2
  - python -m pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - pytest
on_success:
  script: pyinstaller "Number-Plate-Anonymiser/main.spec"
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: "dist/*.exe"
  skip_cleanup: true
  on:
    tags: true